MkEx
CallStack (from HasCallStack):
  throwWithCallStack, called at src/Effects/Exception.hs:0:0 in monad-exceptions-0.0-inplace:Effects.Exception
  throwWithCallStack, called at test/unit/Main.hs:0:0 in main:Main
  throwsCallStack, called at test/unit/Main.hs:0:0 in main:Main